Demostraciones/IronMan/IronManMVC/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IronMan.Dominio.Modelos;
using IronMan.AccesoDatos;
using IronMan.DTO;
using IronMan.Gestores;

namespace IronManMVC.Controllers
{
    public class EventosController : Controller
    {
        #region Declaración del acceso de los datos persistidos
        //El gestor corresponde al modelo en el patron MVC
        private IronManContext db = new IronManContext();
        private EventoGestor _eGestor = new EventoGestor();
        #endregion

        #region Lista de Eventos - Solo GET
        // GET: /Eventos/
        //Recupera la lista de Eventos
        public ActionResult Index()
        {
            return View(_eGestor.Listar().ToList());
        }
        #endregion

        #region Mostrar Uun evento - Solo GET
        // GET: /Eventos/Details/5
        //Muestra los detalles del evento
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            EventoDTO evento = _eGestor.Obtener(id);

            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }
        #endregion

        #region Crear Evento - GET y POST
        // GET: /Eventos/Create
        //
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Eventos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        // Crea un evento
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Nombre,Fecha,Lugar,Comentario,EstaHabilitado")] EventoDTO evento)
        {
            if (ModelState.IsValid)
            {
                _eGestor.Guardar(evento);
                return RedirectToAction("Index");
            }

            return View(evento);
        }
        #endregion

        #region Modificar Evento - GET y POST
        // GET: /Eventos/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventoDTO evento = _eGestor.Obtener(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // POST: /Eventos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        // Guarda la modificaciones del Evento
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Nombre,Fecha,Lugar,Comentario,EstaHabilitado")] EventoDTO evento)
        {
            if (ModelState.IsValid)
            {
                _eGestor.Guardar(evento);
                return RedirectToAction("Index");
            }
            return View(evento);
        }
        #endregion

        #region Eliminar Evento (Dehabilitar) - GET y POST
        // GET: /Eventos/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            EventoDTO evento = _eGestor.Obtener(id); ;
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // POST: /Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventoDTO evento = _eGestor.Obtener(id);
            _eGestor.Deshabilitar(evento);
            return RedirectToAction("Index");
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Demostraciones/IronMan/IronManMVC/Controllers/PruebasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IronMan.Dominio.Modelos;
using IronMan.AccesoDatos;
using IronMan.DTO;
using IronMan.Gestores;

namespace IronManMVC.Controllers
{
    public class PruebasController : Controller
    {
        #region Declaración del acceso de los datos persistidos
        //El gestor corresponde al modelo en el patron MVC
        private IronManContext db = new IronManContext();
        private PruebaGestor _pGestor = new PruebaGestor();
        private EventoGestor _eGestor = new EventoGestor();
        #endregion

        class VistaPrueba
        {
            public List<PruebaDTO> pruebas {set; get; }
            public EventoDTO evento { set; get; }
        }
        // GET: Pruebas
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return View(new VistaPrueba(){pruebas = _pGestor.Listar().ToList(), evento = null});
            }
            else
            {
                return View(new VistaPrueba() { pruebas = _pGestor.Listar(id).ToList(), evento = _eGestor.Obtener() });
            }
        }

        // GET: Pruebas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Pruebas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pruebas/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pruebas/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Pruebas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pruebas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Pruebas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Demostraciones/IronMan/IronManMVC/Views/Eventos/Create.cshtml
@model IronMan.Dominio.Modelos.Evento

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Evento</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre)
                @Html.ValidationMessageFor(model => model.Nombre)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha)
                @Html.ValidationMessageFor(model => model.Fecha)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lugar, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lugar)
                @Html.ValidationMessageFor(model => model.Lugar)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comentario, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comentario)
                @Html.ValidationMessageFor(model => model.Comentario)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstaHabilitado, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstaHabilitado)
                @Html.ValidationMessageFor(model => model.EstaHabilitado)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Demostraciones/IronMan/IronManMVC/Views/Eventos/Delete.cshtml
@model IronMan.Dominio.Modelos.Evento

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Evento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comentario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstaHabilitado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstaHabilitado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Demostraciones/IronMan/IronManMVC/Views/Eventos/Details.cshtml
@model IronMan.Dominio.Modelos.Evento

@{
    ViewBag.Title = "Detalles del Evento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Evento</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comentario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstaHabilitado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstaHabilitado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Volver a la Lista", "Index")
</p>

Demostraciones/IronMan/IronManMVC/Views/Eventos/Edit.cshtml
@model IronMan.Dominio.Modelos.Evento

@{
    ViewBag.Title = "Editar Evento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Evento</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre)
                @Html.ValidationMessageFor(model => model.Nombre)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha)
                @Html.ValidationMessageFor(model => model.Fecha)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lugar, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lugar)
                @Html.ValidationMessageFor(model => model.Lugar)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comentario, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comentario)
                @Html.ValidationMessageFor(model => model.Comentario)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstaHabilitado, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstaHabilitado)
                @Html.ValidationMessageFor(model => model.EstaHabilitado)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la Lista", "Index")
</div>

Demostraciones/IronMan/IronManMVC/Views/Eventos/Index.cshtml
@model IEnumerable<IronMan.Dominio.Modelos.Evento>

@{
    ViewBag.Title = "Lista de Eventos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Nuevo Evento", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lugar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comentario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstaHabilitado)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lugar)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comentario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstaHabilitado)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id }) |
            @Html.ActionLink("Prueba", "Index", "Pruebas", new { id = item.Id }, null)
        </td>
    </tr>
}

</table>